In [1]:
import pandas as pd

In [2]:
df = pd. read_csv('COVID-19_PA_Cases.csv')

In [3]:
df.head(10)

,Jurisdiction,Date,New Cases,7-day Average New Cases,Cumulative cases,Population (2019),New Case Rate,7-Day Average New Case Rate,Cumulative Case Rate,County FIPS Code,Longitude,Latitude,Georeferenced Lat & Long
0,Centre,03/05/2020,0,NaN,0,162385,0.0,NaN,0.0,42027,-77.825001,40.919314,POINT (-77.82500112 40.9193135)
1,Lehigh,03/13/2021,71,82.1,31915,369318,19.2,22.2,8641.6,42077,-75.600995,40.614648,POINT (-75.60099481 40.61464794)
2,Luzerne,08/04/2020,26,20.7,3407,317417,8.2,6.5,1073.4,42079,-75.991996,41.178364,POINT (-75.9919961 41.17836439)
3,Pennsylvania,08/04/2020,754,814.7,116551,12801989,5.9,6.4,910.4,42000,-75.167756,39.346129,POINT (-75.167756 39.346129)
4,Berks,10/29/2020,94,112.4,9494,421164,22.3,26.7,2254.2,42011,-75.930773,40.419396,POINT (-75.93077327 40.41939635)
5,Monroe,07/28/2020,8,5.1,1580,170271,4.7,3.0,927.9,42089,-75.340836,41.060918,POINT (-75.34083603 41.06091787)
6,Monroe,08/18/2020,4,3.4,1684,170271,2.3,2.0,989.0,42089,-75.340836,41.060918,POINT (-75.34083603 41.06091787)
7,Union,05/30/2020,0,0.7,58,44923,0.0,1.6,129.1,42119,-77.064158,40.964731,POINT (-77.06415803 40.96473131)
8,Union,07/08/2020,0,0.6,100,44923,0.0,1.3,222.6,42119,-77.064158,40.964731,POINT (-77.06415803 40.96473131)
9,Philadelphia,01/20/2021,542,512.4,100648,1584064,34.2,32.3,6353.8,42101,-75.140236,40.004444,POINT (-75.140236 40.00444354)

In [4]:
df.tail(10)

,Jurisdiction,Date,New Cases,7-day Average New Cases,Cumulative cases,Population (2019),New Case Rate,7-Day Average New Case Rate,Cumulative Case Rate,County FIPS Code,Longitude,Latitude,Georeferenced Lat & Long
27326,Snyder,09/01/2020,2,3.0,176,40372,5.0,7.4,435.9,42109,-77.072560,40.771137,POINT (-77.07255968 40.77113737)
27327,Elk,10/06/2020,0,1.0,87,29910,0.0,3.3,290.9,42047,-78.649477,41.428194,POINT (-78.64947713 41.42819416)
27328,Elk,10/28/2020,4,5.3,176,29910,13.4,17.7,588.4,42047,-78.649477,41.428194,POINT (-78.64947713 41.42819416)
27329,Elk,10/11/2020,1,0.9,93,29910,3.3,2.9,310.9,42047,-78.649477,41.428194,POINT (-78.64947713 41.42819416)
27330,Snyder,08/23/2020,1,1.9,148,40372,2.5,4.6,366.6,42109,-77.072560,40.771137,POINT (-77.07255968 40.77113737)
27331,Snyder,08/13/2020,3,2.7,125,40372,7.4,6.7,309.6,42109,-77.072560,40.771137,POINT (-77.07255968 40.77113737)
27332,Snyder,08/11/2020,3,2.1,120,40372,7.4,5.3,297.2,42109,-77.072560,40.771137,POINT (-77.07255968 40.77113737)
27333,Elk,11/06/2020,12,12.4,270,29910,40.1,41.6,902.7,42047,-78.649477,41.428194,POINT (-78.64947713 41.42819416)
27334,Snyder,08/10/2020,5,1.7,117,40372,12.4,4.2,289.8,42109,-77.072560,40.771137,POINT (-77.07255968 40.77113737)
27335,Snyder,07/27/2020,3,1.1,96,40372,7.4,2.8,237.8,42109,-77.072560,40.771137,POINT (-77.07255968 40.77113737)

In [5]:
df.sample(10)

,Jurisdiction,Date,New Cases,7-day Average New Cases,Cumulative cases,Population (2019),New Case Rate,7-Day Average New Case Rate,Cumulative Case Rate,County FIPS Code,Longitude,Latitude,Georeferenced Lat & Long
558,Carbon,12/04/2020,70,46.0,1641,64182,109.1,71.7,2556.8,42025,-75.711070,40.919367,POINT (-75.71107039 40.91936701)
18667,Greene,03/27/2020,2,0.9,6,36233,5.5,2.4,16.6,42059,-80.229438,39.854804,POINT (-80.22943817 39.85480393)
596,Columbia,11/18/2020,7,15.1,1291,64964,10.8,23.3,1987.3,42037,-76.410022,41.049121,POINT (-76.4100218 41.04912086)
9806,Venango,05/14/2020,0,0.0,9,50668,0.0,0.0,17.8,42121,-79.762866,41.403413,POINT (-79.76286561 41.40341259)
7783,Pennsylvania,03/30/2021,4372,4054.3,1025442,12801989,34.2,31.7,8010.0,42000,-75.167756,39.346129,POINT (-75.167756 39.346129)
24637,Greene,06/24/2020,0,0.7,39,36233,0.0,2.0,107.6,42059,-80.229438,39.854804,POINT (-80.22943817 39.85480393)
26126,Perry,12/19/2020,28,35.3,1374,46272,60.5,76.3,2969.4,42099,-77.259074,40.404153,POINT (-77.25907385 40.40415317)
24722,Lancaster,12/19/2020,286,359.3,24627,545724,52.4,65.8,4512.7,42071,-76.251388,40.045908,POINT (-76.25138768 40.04590796)
550,Delaware,08/20/2020,38,56.6,10095,566747,6.7,10.0,1781.2,42045,-75.406277,39.916579,POINT (-75.40627712 39.91657867)
4651,Berks,10/02/2020,39,41.4,7320,421164,9.3,9.8,1738.0,42011,-75.930773,40.419396,POINT (-75.93077327 40.41939635)

In [6]:
df.columns

Index(['Jurisdiction', 'Date', 'New Cases', '7-day Average New Cases',
       'Cumulative cases                          ', 'Population (2019)',
       'New Case Rate', '7-Day Average New Case Rate', 'Cumulative Case Rate',
       'County FIPS Code', 'Longitude', 'Latitude',
       'Georeferenced Lat & Long'],
      dtype='object')

In [7]:
dfMini=(['Jurisdiction', 'Date', 'New Cases', 'Cumulative Cases', 'Population (2019)', 'New Case Rate','Cumulative Case Rat'])

In [8]:
dfMini.to_csv('COVID-19_PA_Cases.csv', encoding='utf8')

AttributeError: 'list' object has no attribute 'to_csv'

In [9]:
pwd

'/Users/Troubs/Desktop/pythonforjournalists'

In [10]:
df.sample()

,Jurisdiction,Date,New Cases,7-day Average New Cases,Cumulative cases,Population (2019),New Case Rate,7-Day Average New Case Rate,Cumulative Case Rate,County FIPS Code,Longitude,Latitude,Georeferenced Lat & Long
26177,Huntingdon,06/20/2020,0,0.1,243,45144,0.0,0.3,538.3,42061,-77.982766,40.416105,POINT (-77.9827661 40.416105)

In [11]:
df = df.drop('7-day Average New Cases', 1)

In [12]:
df.sample()

,Jurisdiction,Date,New Cases,Cumulative cases,Population (2019),New Case Rate,7-Day Average New Case Rate,Cumulative Case Rate,County FIPS Code,Longitude,Latitude,Georeferenced Lat & Long
2472,Union,04/29/2020,2,28,44923,4.5,1.6,62.3,42119,-77.064158,40.964731,POINT (-77.06415803 40.96473131)

In [13]:
df = df.drop('7-Day Average New Case Rate', 1)

In [14]:
df = df.drop('County FIPS Code', 1)

In [17]:
df = df.drop('Longitude', 1)

In [18]:
df = df.drop('Latitude', 1)

In [19]:
df = df.drop('Georeferenced Lat & Long', 1)

In [20]:
dfMini.to_csv('COVID-19_PA_Cases.csv', encoding='utf8')

AttributeError: 'list' object has no attribute 'to_csv'

In [21]:
df.sample()

,Jurisdiction,Date,New Cases,Cumulative cases,Population (2019),New Case Rate,Cumulative Case Rate
19036,Westmoreland,08/15/2020,9,1636,348899,2.6,468.9